# Generated by Django 3.2.9 on 2025-11-06 20:55

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20251106_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data', models.DateField(unique=True)),
                ('tipo', models.CharField(choices=[('NACIONAL', 'Nacional'), ('ESTADUAL', 'Estadual'), ('MUNICIPAL', 'Municipal')], max_length=10)),
                ('recorrente', models.BooleanField(default=False, help_text='Se True, o feriado ocorre anualmente na mesma data')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='TransacaoPIX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_pix_destino', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída'), ('FALHA', 'Falha'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10)),
                ('data_transacao', models.DateTimeField(auto_now_add=True)),
                ('identificador_transacao', models.CharField(max_length=100, unique=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('conta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes_pix_recebidas', to='accounts.userbankaccount')),
                ('conta_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes_pix_enviadas', to='accounts.userbankaccount')),
            ],
            options={
                'verbose_name': 'Transação PIX',
                'verbose_name_plural': 'Transações PIX',
                'ordering': ['-data_transacao'],
            },
        ),
        migrations.CreateModel(
            name='ChavePIX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CPF', 'CPF'), ('EMAIL', 'Email'), ('TELEFONE', 'Telefone'), ('ALEATORIA', 'Chave Aleatória')], max_length=10)),
                ('chave', models.CharField(max_length=255, unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_inativacao', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaves_pix', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chave PIX',
                'verbose_name_plural': 'Chaves PIX',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacao', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('SAQUE', 'Saque'), ('TRANSFERENCIA', 'Transferência'), ('PIX', 'PIX'), ('JUROS', 'Juros')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_posterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hash_registro', models.CharField(max_length=64, unique=True)),
                ('hash_anterior', models.CharField(blank=True, max_length=64, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='accounts.userbankaccount')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='localizatio_timesta_3ad022_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['usuario', '-timestamp'], name='localizatio_usuario_0431e6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['conta', '-timestamp'], name='localizatio_conta_i_8bb241_idx'),
        ),
    ]
