# Generated by Django 3.2.9 on 2025-11-06 20:55

from django.db import migrations
from datetime import date


def populate_holidays(apps, schema_editor):
    """Popula feriados nacionais brasileiros"""
    Feriado = apps.get_model('localization', 'Feriado')
    
    feriados_2024 = [
        ('Ano Novo', date(2024, 1, 1), 'NACIONAL', True),
        ('Carnaval', date(2024, 2, 13), 'NACIONAL', False),
        ('Sexta-feira Santa', date(2024, 3, 29), 'NACIONAL', False),
        ('Tiradentes', date(2024, 4, 21), 'NACIONAL', True),
        ('Dia do Trabalho', date(2024, 5, 1), 'NACIONAL', True),
        ('Corpus Christi', date(2024, 5, 30), 'NACIONAL', False),
        ('Independência do Brasil', date(2024, 9, 7), 'NACIONAL', True),
        ('Nossa Senhora Aparecida', date(2024, 10, 12), 'NACIONAL', True),
        ('Finados', date(2024, 11, 2), 'NACIONAL', True),
        ('Proclamação da República', date(2024, 11, 15), 'NACIONAL', True),
        ('Dia da Consciência Negra', date(2024, 11, 20), 'NACIONAL', False),
        ('Natal', date(2024, 12, 25), 'NACIONAL', True),
    ]
    
    feriados_2025 = [
        ('Ano Novo', date(2025, 1, 1), 'NACIONAL', True),
        ('Carnaval', date(2025, 3, 4), 'NACIONAL', False),
        ('Sexta-feira Santa', date(2025, 4, 18), 'NACIONAL', False),
        ('Tiradentes', date(2025, 4, 21), 'NACIONAL', True),
        ('Dia do Trabalho', date(2025, 5, 1), 'NACIONAL', True),
        ('Corpus Christi', date(2025, 6, 19), 'NACIONAL', False),
        ('Independência do Brasil', date(2025, 9, 7), 'NACIONAL', True),
        ('Nossa Senhora Aparecida', date(2025, 10, 12), 'NACIONAL', True),
        ('Finados', date(2025, 11, 2), 'NACIONAL', True),
        ('Proclamação da República', date(2025, 11, 15), 'NACIONAL', True),
        ('Dia da Consciência Negra', date(2025, 11, 20), 'NACIONAL', False),
        ('Natal', date(2025, 12, 25), 'NACIONAL', True),
    ]
    
    for nome, data_feriado, tipo, recorrente in feriados_2024 + feriados_2025:
        Feriado.objects.get_or_create(
            data=data_feriado,
            defaults={
                'nome': nome,
                'tipo': tipo,
                'recorrente': recorrente
            }
        )


def convert_account_numbers(apps, schema_editor):
    """Converte account_no existentes para formato agencia/conta brasileiro"""
    UserBankAccount = apps.get_model('accounts', 'UserBankAccount')
    
    for account in UserBankAccount.objects.all():
        if not account.agencia or not account.conta:
            account_str = str(account.account_no).zfill(11)
            account.agencia = account_str[:4]
            conta_base = account_str[4:10]
            dv = int(account_str[10]) if len(account_str) > 10 else 0
            account.conta = f"{conta_base}-{dv}"
            account.save()


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0001_initial'),
        ('accounts', '0002_auto_20251106_2055'),
    ]

    operations = [
        migrations.RunPython(populate_holidays, migrations.RunPython.noop),
        migrations.RunPython(convert_account_numbers, migrations.RunPython.noop),
    ]
