# Generated by Django 3.2.9 on 2025-11-06 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20251106_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualTaxReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_interest', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pix_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_pix_sent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, upload_to='tax_reports/')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_reports', to='accounts.userbankaccount')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('account', 'year')},
            },
        ),
    ]
