spring.application.name=Sistema Banco

server.port=8080

spring.datasource.url=jdbc:h2:file:./data/bankingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.thymeleaf.cache=false

banking.account.starting-number=1000000000
banking.transaction.minimum-deposit=10.00
banking.transaction.minimum-withdrawal=10.00

spring.profiles.active=demo
