# Generated by Django 3.2.9 on 2025-11-06 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('CREATE_USER', 'Create User'), ('CREATE_ACCOUNT', 'Create Account'), ('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('PIX_REGISTER_KEY', 'PIX Register Key'), ('PIX_TRANSFER', 'PIX Transfer'), ('PIX_GENERATE_QR', 'PIX Generate QR Code'), ('INTEREST_CALC', 'Interest Calculation')], max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='core_auditl_timesta_80074f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action'], name='core_auditl_user_id_4f5b78_idx'),
        ),
    ]
