SENIOR_ADMIN = 'SENIOR'
OPERATIONAL_ADMIN = 'OPERATIONAL'
VIEWER = 'VIEWER'

ADMIN_ROLE_CHOICES = (
    (SENIOR_ADMIN, 'Senior Admin'),
    (OPERATIONAL_ADMIN, 'Operational Admin'),
    (VIEWER, 'Viewer'),
)

ACTION_CREATE = 'CREATE'
ACTION_UPDATE = 'UPDATE'
ACTION_DELETE = 'DELETE'
ACTION_SUSPEND = 'SUSPEND'
ACTION_REACTIVATE = 'REACTIVATE'
ACTION_VIEW = 'VIEW'

AUDIT_ACTION_CHOICES = (
    (ACTION_CREATE, 'Create'),
    (ACTION_UPDATE, 'Update'),
    (ACTION_DELETE, 'Delete'),
    (ACTION_SUSPEND, 'Suspend'),
    (ACTION_REACTIVATE, 'Reactivate'),
    (ACTION_VIEW, 'View'),
)

FRAUD_SUSPICIOUS_WITHDRAWAL = 'SUSPICIOUS_WITHDRAWAL'
FRAUD_UNUSUAL_HOURS = 'UNUSUAL_HOURS'
FRAUD_REPEATED_TRANSACTIONS = 'REPEATED_TRANSACTIONS'
FRAUD_EXCEEDS_MAX_AMOUNT = 'EXCEEDS_MAX_AMOUNT'

FRAUD_RULE_CHOICES = (
    (FRAUD_SUSPICIOUS_WITHDRAWAL, 'Suspicious Withdrawal'),
    (FRAUD_UNUSUAL_HOURS, 'Unusual Hours'),
    (FRAUD_REPEATED_TRANSACTIONS, 'Repeated Transactions'),
    (FRAUD_EXCEEDS_MAX_AMOUNT, 'Exceeds Maximum Amount'),
)

ALERT_PENDING = 'PENDING'
ALERT_REVIEWED = 'REVIEWED'
ALERT_FALSE_POSITIVE = 'FALSE_POSITIVE'

ALERT_STATUS_CHOICES = (
    (ALERT_PENDING, 'Pending'),
    (ALERT_REVIEWED, 'Reviewed'),
    (ALERT_FALSE_POSITIVE, 'False Positive'),
)

HEALTH_CPU = 'CPU'
HEALTH_MEMORY = 'MEMORY'
HEALTH_NETWORK = 'NETWORK'
HEALTH_DB_RESPONSE = 'DB_RESPONSE'
HEALTH_CELERY = 'CELERY'
HEALTH_REDIS = 'REDIS'

HEALTH_METRIC_CHOICES = (
    (HEALTH_CPU, 'CPU Usage'),
    (HEALTH_MEMORY, 'Memory Usage'),
    (HEALTH_NETWORK, 'Network'),
    (HEALTH_DB_RESPONSE, 'Database Response Time'),
    (HEALTH_CELERY, 'Celery Worker Status'),
    (HEALTH_REDIS, 'Redis Status'),
)

SEVERITY_LOW = 'LOW'
SEVERITY_MEDIUM = 'MEDIUM'
SEVERITY_HIGH = 'HIGH'
SEVERITY_CRITICAL = 'CRITICAL'

SEVERITY_CHOICES = (
    (SEVERITY_LOW, 'Low'),
    (SEVERITY_MEDIUM, 'Medium'),
    (SEVERITY_HIGH, 'High'),
    (SEVERITY_CRITICAL, 'Critical'),
)
