# Generated by Django 5.0 on 2025-11-06 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_userbankaccount_cpf'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TRANSACTION_CREATE', 'Transação Criada'), ('TRANSACTION_MODIFY', 'Transação Modificada'), ('ACCOUNT_CREATE', 'Conta Criada'), ('ACCOUNT_MODIFY', 'Conta Modificada'), ('ACCOUNT_SUSPEND', 'Conta Suspensa'), ('FRAUD_ALERT', 'Alerta de Fraude'), ('LOGIN_SUCCESS', 'Login Bem-sucedido'), ('LOGIN_FAILURE', 'Tentativa de Login Falhou')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.userbankaccount')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='transactions.transaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_log_a_timesta_e00a3a_idx'), models.Index(fields=['event_type', '-timestamp'], name='audit_log_a_event_t_59a64b_idx'), models.Index(fields=['account', '-timestamp'], name='audit_log_a_account_38b2e1_idx')],
            },
        ),
    ]
