# Generated by Django 5.0.14 on 2025-11-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeriadoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('NACIONAL', 'Nacional'), ('ESTADUAL', 'Estadual'), ('MUNICIPAL', 'Municipal')], default='NACIONAL', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feriado Bancário',
                'verbose_name_plural': 'Feriados Bancários',
                'ordering': ['data'],
                'indexes': [models.Index(fields=['data', 'ativo'], name='calendario__data_634b2c_idx')],
            },
        ),
    ]
