DEPOSIT = 1
WITHDRAWAL = 2
INTEREST = 3

TRANSACTION_TYPE_CHOICES = (
    (DEPOSIT, 'Deposit'),
    (WITHDRAWAL, 'Withdrawal'),
    (INTEREST, 'Interest'),
)

DEPOSIT_ATTEMPT = 'DEPOSIT_ATTEMPT'
DEPOSIT_SUCCESS = 'DEPOSIT_SUCCESS'
WITHDRAW_ATTEMPT = 'WITHDRAW_ATTEMPT'
WITHDRAW_SUCCESS = 'WITHDRAW_SUCCESS'
INTEREST_CALCULATION = 'INTEREST_CALCULATION'
TRANSACTION_MODIFICATION_ATTEMPT = 'TRANSACTION_MODIFICATION_ATTEMPT'

AUDIT_ACTION_CHOICES = (
    (DEPOSIT_ATTEMPT, 'Deposit Attempt'),
    (DEPOSIT_SUCCESS, 'Deposit Success'),
    (WITHDRAW_ATTEMPT, 'Withdraw Attempt'),
    (WITHDRAW_SUCCESS, 'Withdraw Success'),
    (INTEREST_CALCULATION, 'Interest Calculation'),
    (TRANSACTION_MODIFICATION_ATTEMPT, 'Transaction Modification Attempt'),
)
