# Generated by Django 5.0 on 2025-11-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField(auto_now_add=True)),
                ('total_users', models.IntegerField(default=0)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_interest', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['-metric_date'],
            },
        ),
    ]
