# Generated by Django 3.2.9 on 2025-11-06 20:53

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbankaccount',
            name='account_no',
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(default='123.456.789-09', max_length=14, unique=True, validators=[accounts.validators.validate_cpf]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='account_digit',
            field=models.CharField(default='0', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='account_number',
            field=models.CharField(default='0000001000', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='agency',
            field=models.CharField(default='0001', max_length=4),
            preserve_default=False,
        ),
    ]
