# Generated by Django 3.2.9 on 2025-11-06 20:43

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(default='00000000191', help_text='CPF no formato XXX.XXX.XXX-XX ou XXXXXXXXXXX', max_length=14, unique=True, validators=[accounts.validators.validate_cpf]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='agencia',
            field=models.CharField(default='0001', help_text='4-digit agency number', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='conta',
            field=models.CharField(default='00000001', help_text='8-digit account number', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='digito_verificador',
            field=models.CharField(default='0', help_text='Check digit', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_no',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
