# Generated by Django 3.2.9 on 2025-11-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbankaccount',
            options={'permissions': [('can_approve_transactions', 'Can approve transactions'), ('can_view_all_accounts', 'Can view all accounts'), ('can_manage_users', 'Can manage users')]},
        ),
    ]
