# Generated by Django 3.2.9 on 2025-11-06 20:59

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='agencia',
            field=models.CharField(default='0001', help_text='Agência (4 dígitos)', max_length=4),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='cpf',
            field=models.CharField(default='000.000.001-91', help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, unique=True, validators=[accounts.models.validate_cpf]),
            preserve_default=False,
        ),
    ]
