# Generated by Django 3.2.9 on 2025-11-06 20:55

from django.db import migrations, models
import localization.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, null=True, unique=True, validators=[localization.validators.validate_cpf]),
        ),
        migrations.AddField(
            model_name='user',
            name='cpf_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='agencia',
            field=models.CharField(blank=True, help_text='Número da agência (4 dígitos)', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='conta',
            field=models.CharField(blank=True, help_text='Número da conta com dígito verificador (6 dígitos + 1 DV)', max_length=7, null=True),
        ),
    ]
