# Generated by Django 3.2.9 on 2025-11-06 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('high_value', 'High Value Transaction'), ('high_frequency', 'High Frequency Transactions'), ('unusual_hours', 'Unusual Hours'), ('pattern_change', 'Pattern Change')], help_text='Type of fraud detection rule', max_length=50)),
                ('parameters', models.JSONField(help_text='Rule-specific parameters in JSON format')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Severity level of this fraud rule', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Review status of this suspicious transaction', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about the review of this transaction')),
                ('fraud_rules', models.ManyToManyField(help_text='Fraud rules that were violated', related_name='suspicious_transactions', to='accounts.FraudRule')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suspicious_transactions', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-detected_at'],
                'permissions': [('can_manage_fraud_rules', 'Can manage fraud detection rules'), ('can_review_suspicious_transactions', 'Can review suspicious transactions')],
            },
        ),
    ]
