# Generated by Django 3.2.9 on 2025-11-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('MANAGER', 'Manager'), ('ANALYST', 'Analyst'), ('SUPPORT', 'Support'), ('REGULAR_USER', 'Regular User')], default='REGULAR_USER', max_length=20),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='alto_risco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='conta_suspensa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='verificacao_pendente',
            field=models.BooleanField(default=False),
        ),
    ]
