# Generated by Django 3.2.9 on 2025-11-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('auditor', 'Auditor')], max_length=20, null=True),
        ),
    ]
