# Generated by Django 3.2.9 on 2025-11-06 20:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(default='111.444.777-35', help_text='CPF no formato ###.###.###-##', max_length=14, unique=True, validators=[accounts.models.validate_cpf]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='account_check_digit',
            field=models.CharField(default='0', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='bank_code',
            field=models.CharField(default='237', max_length=3),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='branch_code',
            field=models.CharField(default='0001', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
