# Generated by Django 3.2.9 on 2025-11-06 20:43

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='agencia',
            field=models.CharField(default='0001', max_length=4, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='conta',
            field=models.CharField(default='0000000001', max_length=10, verbose_name='Conta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='cpf',
            field=localflavor.br.models.BRCPFField(default='000.000.000-00', max_length=14, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='digito_verificador',
            field=models.CharField(default='0', max_length=1, verbose_name='Dígito Verificador'),
            preserve_default=False,
        ),
    ]
