# Generated by Django 3.2.9 on 2025-11-06 20:25

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF number (11 digits)', max_length=11, null=True, unique=True, validators=[accounts.validators.validate_cpf]),
        ),
    ]
