# Generated by Django 3.2.9 on 2025-11-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='account_number',
            field=models.CharField(default='0000000', help_text='Número da conta (7 dígitos)', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='agency',
            field=models.CharField(default='0001', help_text='Agência bancária (4 dígitos)', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='check_digit',
            field=models.CharField(default='0', help_text='Dígito verificador (1 dígito)', max_length=1),
            preserve_default=False,
        ),
    ]
