# Generated by Django 3.2.9 on 2025-11-06 20:51

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF (somente números, 11 dígitos)', max_length=11, null=True, unique=True, validators=[accounts.validators.validate_cpf]),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='agencia',
            field=models.CharField(default='0001', max_length=4),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='digito_verificador',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='numero_conta',
            field=models.CharField(default='', max_length=10),
        ),
    ]
