# Generated by Django 3.2.9 on 2025-11-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userbankaccount',
            index=models.Index(fields=['balance', 'interest_start_date'], name='account_balance_interest_idx'),
        ),
        migrations.AddIndex(
            model_name='userbankaccount',
            index=models.Index(fields=['initial_deposit_date'], name='account_initial_deposit_idx'),
        ),
    ]
