# Generated by Django 3.2.9 on 2025-11-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_permissions',
            field=models.JSONField(blank=True, default=list, help_text='List of admin permissions: VIEW_USERS, EDIT_USERS, SUSPEND_USERS, VIEW_REPORTS'),
        ),
    ]
