# Generated by Django 3.2.9 on 2025-11-06 20:37

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='account_digit',
            field=models.CharField(default='0', help_text='Dígito verificador', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='account_number',
            field=models.CharField(default='00000000', help_text='Número da conta (até 8 dígitos)', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='agency',
            field=models.CharField(default='0001', help_text='Agência (4 dígitos)', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='cpf',
            field=models.CharField(default='11144477735', help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, unique=True, validators=[accounts.validators.validate_cpf_format, accounts.validators.validate_cpf_digits]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_no',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
