# Generated by Django 5.0.14 on 2025-11-06 21:18

import accounts.encrypted_fields
import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_bankaccounttype_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=accounts.encrypted_fields.EncryptedCharField(blank=True, help_text='CPF no formato XXX.XXX.XXX-XX', max_length=14, null=True, unique=True, validators=[accounts.validators.validate_cpf]),
        ),
        migrations.AddField(
            model_name='user',
            name='lgpd_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='lgpd_consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='agencia',
            field=models.CharField(blank=True, help_text='4 dígitos da agência', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='conta',
            field=models.CharField(blank=True, help_text='Até 10 dígitos da conta', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='digito_verificador',
            field=models.CharField(blank=True, help_text='Dígito verificador', max_length=1, null=True),
        ),
    ]
