# Generated by Django 5.0.9 on 2025-11-06 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_bankaccounttype_id_alter_user_id_and_more'),
        ('accounts', '0004_add_cpf_to_userbankaccount'),
    ]

    operations = [
    ]
