# Generated by Django 5.0.9 on 2025-11-06 21:14

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20251106_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do usuário (apenas números)', max_length=11, null=True, unique=True, validators=[accounts.models.validate_cpf]),
        ),
    ]
