# Generated by Django 5.0.9 on 2025-11-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_suspended'),
        ('accounts', '0006_user_cpf'),
    ]

    operations = [
    ]
