# Generated by Django 5.0.9 on 2025-11-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20251106_2113'),
        ('accounts', '0007_merge_0002_user_is_suspended_0006_user_cpf'),
    ]

    operations = [
    ]
