# Generated by Django 3.2.9 on 2025-11-06 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20251106_1759'),
        ('transactions', '0002_auto_20251106_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(choices=[('CPF', 'CPF'), ('EMAIL', 'E-mail'), ('PHONE', 'Telefone'), ('RANDOM', 'Chave Aleatória')], max_length=10)),
                ('key_value', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_keys', to='accounts.userbankaccount')),
            ],
            options={
                'unique_together': {('account', 'key_type')},
            },
        ),
        migrations.CreateModel(
            name='PixTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Concluída'), ('FAILED', 'Falhou')], default='COMPLETED', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_sent', to='accounts.userbankaccount')),
                ('to_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_received', to='pix.pixkey')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
