# Generated by Django 3.2.9 on 2025-11-06 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.PositiveSmallIntegerField(choices=[(1, 'CPF'), (2, 'Email'), (3, 'Telefone'), (4, 'Chave Aleatória')])),
                ('key_value', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_keys', to='accounts.userbankaccount')),
            ],
            options={
                'unique_together': {('account', 'key_type', 'key_value')},
            },
        ),
        migrations.CreateModel(
            name='PixTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sender_balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receiver_balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_received', to='accounts.userbankaccount')),
                ('receiver_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_received', to='pix.pixkey')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_sent', to='accounts.userbankaccount')),
                ('sender_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_sent', to='pix.pixkey')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
