# Generated by Django 5.0.14 on 2025-11-06 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_cpf_user_lgpd_consent_user_lgpd_consent_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChavePix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CPF', 'CPF'), ('EMAIL', 'Email'), ('CELULAR', 'Celular'), ('ALEATORIA', 'Chave Aleatória')], max_length=20)),
                ('valor', models.CharField(help_text='Valor da chave PIX', max_length=200, unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaves_pix', to='accounts.userbankaccount')),
            ],
            options={
                'verbose_name': 'Chave PIX',
                'verbose_name_plural': 'Chaves PIX',
            },
        ),
        migrations.CreateModel(
            name='TransacaoPix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(blank=True, help_text='Descrição da transferência (máximo 140 caracteres)', max_length=140)),
                ('qr_code_payload', models.TextField(blank=True, help_text='Payload do QR Code EMVCo')),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('FALHOU', 'Falhou')], default='PROCESSANDO', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chave_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_recebidas', to='pix.chavepix')),
                ('conta_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_recebidos', to='accounts.userbankaccount')),
                ('conta_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_enviados', to='accounts.userbankaccount')),
            ],
            options={
                'verbose_name': 'Transação PIX',
                'verbose_name_plural': 'Transações PIX',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='chavepix',
            index=models.Index(fields=['conta', 'ativa'], name='pix_chavepi_conta_i_418c27_idx'),
        ),
        migrations.AddIndex(
            model_name='transacaopix',
            index=models.Index(fields=['conta_origem', '-timestamp'], name='pix_transac_conta_o_e6587d_idx'),
        ),
        migrations.AddIndex(
            model_name='transacaopix',
            index=models.Index(fields=['conta_destino', '-timestamp'], name='pix_transac_conta_d_b62fd3_idx'),
        ),
    ]
