# Generated by Django 5.0.14 on 2025-11-06 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioIRPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_calendario', models.IntegerField(db_index=True)),
                ('rendimentos_juros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_depositado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sacado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_31_dezembro', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('arquivo_pdf', models.FileField(blank=True, upload_to='irpf/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_irpf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório IRPF',
                'verbose_name_plural': 'Relatórios IRPF',
                'ordering': ['-ano_calendario', '-gerado_em'],
                'unique_together': {('usuario', 'ano_calendario')},
            },
        ),
    ]
