# Generated by Django 3.2.9 on 2025-11-06 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChavePix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CPF', 'CPF'), ('EMAIL', 'Email'), ('TELEFONE', 'Telefone'), ('ALEATORIA', 'Chave Aleatória')], max_length=10)),
                ('chave', models.CharField(max_length=255, unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaves_pix', to='accounts.userbankaccount')),
            ],
            options={
                'verbose_name_plural': 'Chaves PIX',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after_transaction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Interest'), (4, 'PIX Enviado'), (5, 'PIX Recebido')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('geolocation', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('pix_destinatario_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('pix_destinatario_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('pix_chave', models.CharField(blank=True, max_length=255, null=True)),
                ('pix_txid', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.userbankaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaPix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_destino_valor', models.CharField(max_length=255)),
                ('chave_destino_tipo', models.CharField(max_length=10)),
                ('qr_code_data', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Concluída'), ('FAILED', 'Falha')], default='COMPLETED', max_length=20)),
                ('chave_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to='transactions.chavepix')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pix_transfer', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Transferência PIX',
                'verbose_name_plural': 'Transferências PIX',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['timestamp'], name='transaction_timesta_20dac7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='transaction_transac_09d7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['pix_txid'], name='transaction_pix_txi_eb5a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='chavepix',
            index=models.Index(fields=['chave'], name='transaction_chave_3c4dda_idx'),
        ),
    ]
