# Generated by Django 3.2.9 on 2025-11-06 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20251106_2055'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIXKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(choices=[('CPF', 'CPF'), ('EMAIL', 'E-mail'), ('PHONE', 'Telefone'), ('RANDOM', 'Chave Aleatória')], max_length=10)),
                ('key_value', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'key_type', 'key_value')},
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Interest'), (4, 'PIX Transfer')]),
        ),
        migrations.CreateModel(
            name='PIXTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('end_to_end_id', models.CharField(max_length=32, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Concluída'), ('FAILED', 'Falhou')], default='PENDING', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_sent', to='accounts.userbankaccount')),
                ('to_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_received', to='transactions.pixkey')),
            ],
        ),
        migrations.CreateModel(
            name='PIXQRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('qr_code_data', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pix_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='transactions.pixkey')),
            ],
        ),
    ]
