# Generated by Django 3.2.9 on 2025-11-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='integrity_hash',
            field=models.CharField(default='686e02925c64649e56f3be0415b7efda559ff147d3510c563e1ab537cc2fce3c', editable=False, help_text='Hash SHA-256 para integridade', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP de origem da transação', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_agent',
            field=models.CharField(blank=True, help_text='User agent do navegador', max_length=255),
        ),
    ]
