# Generated by Django 3.2.9 on 2025-11-06 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('INVESTIGATING', 'Em Investigação'), ('RESOLVED', 'Resolvido'), ('FALSE_POSITIVE', 'Falso Positivo')], default='PENDING', max_length=20)),
                ('description', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='accounts.userbankaccount')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.fraudpattern')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
