# Generated by Django 3.2.9 on 2025-11-06 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChavePix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_chave', models.CharField(choices=[('CPF', 'CPF'), ('EMAIL', 'Email'), ('TELEFONE', 'Telefone'), ('ALEATORIA', 'Chave Aleatória')], max_length=10)),
                ('chave', models.CharField(max_length=255, unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaves_pix', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Chaves PIX',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Interest'), (4, 'PIX')]),
        ),
        migrations.CreateModel(
            name='TransacaoPix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_destino', models.CharField(max_length=255)),
                ('qr_code_data', models.TextField(blank=True, null=True)),
                ('chave_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_enviadas', to='transactions.chavepix')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pix_data', to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioIRPF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_calendario', models.IntegerField()),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('rendimentos_totais', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rendimentos_isentos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rendimentos_tributaveis', models.DecimalField(decimal_places=2, max_digits=12)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='irpf_reports/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_irpf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório IRPF',
                'verbose_name_plural': 'Relatórios IRPF',
                'ordering': ['-ano_calendario'],
                'unique_together': {('user', 'ano_calendario')},
            },
        ),
    ]
