# Generated by Django 3.2.9 on 2025-11-06 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.PositiveSmallIntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Interest')], help_text='Type of operation performed')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Account balance before the operation', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Account balance after the operation', max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the operation occurred')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user (if applicable)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the operation')),
                ('account', models.ForeignKey(help_text='Account affected by the operation', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.userbankaccount')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the operation (null for system operations)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='transaction_timesta_da7b66_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['account', '-timestamp'], name='transaction_account_11fddb_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='transaction_user_id_374f51_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['operation_type', '-timestamp'], name='transaction_operati_c56829_idx'),
        ),
    ]
