# Generated by Django 3.2.9 on 2025-11-06 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Depósito'), (2, 'Saque'), (3, 'Juros'), (4, 'Transferência PIX')]),
        ),
        migrations.CreateModel(
            name='PIXTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e2e_id', models.CharField(help_text='End-to-End ID for PIX transaction', max_length=255, unique=True)),
                ('payer_info', models.JSONField()),
                ('payee_info', models.JSONField()),
                ('pix_key_used', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pix_details', to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='PIXKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(choices=[('CPF', 'CPF'), ('EMAIL', 'Email'), ('PHONE', 'Telefone'), ('RANDOM', 'Chave Aleatória')], max_length=10)),
                ('key_value', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'key_type', 'key_value')},
            },
        ),
    ]
