# Generated by Django 3.2.9 on 2025-11-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the banking holiday', unique=True)),
                ('name', models.CharField(help_text='Name of the holiday', max_length=255)),
                ('is_national', models.BooleanField(default=True, help_text='Whether this is a national holiday')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddIndex(
            model_name='bankingholiday',
            index=models.Index(fields=['date'], name='transaction_date_78adfd_idx'),
        ),
    ]
