# Generated by Django 3.2.9 on 2025-11-06 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20251106_1737'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(max_length=10)),
                ('key_value', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_keys', to='accounts.userbankaccount')),
            ],
            options={
                'unique_together': {('account', 'key_type')},
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Interest'), (4, 'PIX Sent'), (5, 'PIX Received')]),
        ),
        migrations.CreateModel(
            name='PixTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('pix_key_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.pixkey')),
                ('receiver_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pix_received', to='accounts.userbankaccount')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pix_sent', to='accounts.userbankaccount')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pix_detail', to='transactions.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='PixQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_type', models.CharField(choices=[('STATIC', 'Static'), ('DYNAMIC', 'Dynamic')], max_length=10)),
                ('qr_code_data', models.TextField(help_text='QR code payload')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount for dynamic QR codes', max_digits=12, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pix_qr_codes', to='accounts.userbankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action performed', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('current_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('data_snapshot', models.JSONField(help_text='Snapshot of transaction data')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='transactions.transaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
