# Generated by Django 3.2.9 on 2025-11-06 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_before_transaction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Account balance before this transaction was applied', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the user who performed this transaction', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='operation_source',
            field=models.CharField(choices=[('web', 'Web'), ('api', 'API'), ('admin', 'Admin'), ('system', 'System')], db_index=True, default='web', help_text='Source of the operation', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='User who performed this transaction (null for system operations)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent string from the browser/client', null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['timestamp', 'account'], name='transaction_timesta_95b8d2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'timestamp'], name='transaction_transac_048ad1_idx'),
        ),
    ]
