# Generated by Django 3.2.9 on 2025-11-06 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(help_text='Type of action performed (e.g., deposit, withdrawal, interest)', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Account balance before the transaction', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Account balance after the transaction', max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who initiated the transaction', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string for security monitoring', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context and metadata for forensic analysis')),
                ('transaction', models.ForeignKey(help_text='Associated transaction record', on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='transactions.transaction')),
                ('user', models.ForeignKey(help_text='User who initiated the transaction', on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='transaction_timesta_da7b66_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='transaction_user_id_374f51_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', '-timestamp'], name='transaction_action__2c3c91_idx'),
        ),
    ]
