# Generated by Django 3.2.9 on 2025-11-06 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.PositiveSmallIntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Interest')], help_text='Type of operation: deposit, withdrawal, or interest')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, help_text='Account balance before the operation', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Account balance after the operation', max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the operation occurred')),
                ('description', models.TextField(blank=True, help_text='Additional context or notes about the operation')),
                ('account', models.ForeignKey(help_text='Account affected by the operation', on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='accounts.userbankaccount')),
                ('transaction', models.ForeignKey(help_text='Related transaction record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='transactions.transaction')),
                ('user', models.ForeignKey(help_text='User who performed the operation', on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
