# Generated by Django 3.2.9 on 2025-11-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='geolocation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='hash_signature',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Interest'), (4, 'PIX Transfer')]),
        ),
    ]
