# Generated by Django 3.2.25 on 2025-11-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='transaction',
            index_together={('account', 'timestamp')},
        ),
    ]
