# Generated by Django 3.2.25 on 2025-11-06 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='related_account',
            field=models.ForeignKey(blank=True, help_text='The other account involved in a transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='accounts.userbankaccount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal'), (3, 'Interest'), (4, 'Transfer Sent'), (5, 'Transfer Received')]),
        ),
    ]
