# Generated by Django 3.2.9 on 2025-11-06 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request origin', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information', null=True)),
                ('action_type', models.CharField(choices=[('DEPOSIT_ATTEMPT', 'Deposit Attempt'), ('DEPOSIT_SUCCESS', 'Deposit Success'), ('WITHDRAW_ATTEMPT', 'Withdraw Attempt'), ('WITHDRAW_SUCCESS', 'Withdraw Success'), ('INTEREST_CALCULATION', 'Interest Calculation'), ('TRANSACTION_MODIFICATION_ATTEMPT', 'Transaction Modification Attempt')], max_length=50)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed', null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount involved in the action', max_digits=12, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, help_text='Related transaction if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='transactions.transaction')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action. Null for system actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='transaction_timesta_da7b66_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='transaction_user_id_374f51_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', '-timestamp'], name='transaction_action__2c3c91_idx'),
        ),
    ]
