# Generated by Django 5.0.13 on 2025-11-06 21:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_alter_chavepix_id_alter_transaction_id_and_more"),
        ("transactions", "0002_fraudalert"),
    ]

    operations = []
