# Generated by Django 5.0.13 on 2025-11-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0003_merge_20251106_2115"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fraudalert",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
