# Generated by Django 3.2.9 on 2025-11-06 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20251106_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRPFReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_interest_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('report_file', models.FileField(blank=True, upload_to='irpf_reports/')),
                ('csv_file', models.FileField(blank=True, upload_to='irpf_reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irpf_reports', to='accounts.userbankaccount')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('account', 'year')},
            },
        ),
    ]
