# Generated by Django 5.0 on 2025-11-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankingHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('FEDERAL', 'Feriado Nacional'), ('BANKING', 'Feriado Bancário'), ('OPTIONAL', 'Ponto Facultativo')], default='FEDERAL', max_length=20)),
                ('is_recurring', models.BooleanField(default=True, help_text='Se True, o feriado se repete anualmente na mesma data')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feriado Bancário',
                'verbose_name_plural': 'Feriados Bancários',
                'ordering': ['date'],
                'unique_together': {('date', 'name')},
            },
        ),
    ]
