# Generated by Django 3.2.9 on 2025-11-06 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20251106_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(editable=False, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('previous_hash', models.CharField(editable=False, max_length=64)),
                ('current_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(editable=False)),
                ('user_agent', models.TextField(editable=False)),
                ('additional_data', models.JSONField(default=dict, editable=False)),
                ('account', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userbankaccount')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['account'], name='audit_audit_account_974d33_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['current_hash'], name='audit_audit_current_1c4842_idx'),
        ),
    ]
