# Generated by Django 3.2.9 on 2025-11-06 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('tipo_transacao', models.CharField(editable=False, max_length=50, verbose_name='Tipo de Transação')),
                ('dados_transacao', models.JSONField(editable=False, verbose_name='Dados da Transação')),
                ('hash_anterior', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Hash da Transação Anterior')),
                ('hash_atual', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Hash da Transação Atual')),
                ('usuario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['timestamp'],
            },
        ),
    ]
