# Generated by Django 5.0.14 on 2025-11-06 21:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_cpf_user_lgpd_consent_user_lgpd_consent_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacenAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evento_tipo', models.CharField(choices=[('USER_CREATED', 'Usuário Criado'), ('USER_UPDATED', 'Usuário Atualizado'), ('ACCOUNT_CREATED', 'Conta Criada'), ('ACCOUNT_UPDATED', 'Conta Atualizada'), ('TRANSACTION_CREATED', 'Transação Criada'), ('PIX_TRANSFER', 'Transferência PIX'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], db_index=True, max_length=50)),
                ('dados_anteriores', models.JSONField(blank=True, default=dict)),
                ('dados_posteriores', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('hash_integridade', models.CharField(editable=False, max_length=64)),
                ('hash_anterior', models.CharField(blank=True, editable=False, max_length=64, null=True)),
                ('conta_afetada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userbankaccount')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria BACEN',
                'verbose_name_plural': 'Logs de Auditoria BACEN',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'evento_tipo'], name='compliance__timesta_6b9c44_idx'), models.Index(fields=['usuario', '-timestamp'], name='compliance__usuario_3c0a31_idx')],
            },
        ),
    ]
